[workspace]
authors = ["ines <ines.manour@ens.uvsq.fr>"]
channels = ["conda-forge", "bioconda"]
name = "projet"
platforms = ["linux-64" , "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
numpy = ">=2.3.3,<3"
pandas = ">=2.3.2,<3"
biopython = ">=1.85,<2"
matplotlib = ">=3.10.6,<4"
dssp = ">=4.5.6,<5"
gemmi = { version = ">=0.7.3,<0.8", channel = "conda-forge" }
